apiVersion: v1
kind: Namespace
metadata:
  name: web-app

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-pvc
  namespace: web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: lblanc/web-app
          image: lblanc/web-app
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-app-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-app-volume
          persistentVolumeClaim:
            claimName: web-app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
